services:
    feasibility-test-client:
        build: .
        # entrypoint: bash -c "tail -f /dev/null"
        environment:
            - BACKEND_BASE_URL=${BACKEND_BASE_URL:-"https://localhost/api/v1"} 
            - BACKEND_CLIENT_ID=${BACKEND_CLIENT_ID:-"feasibility-gui"} 
            - BACKEND_CLIENT_SECRET=${BACKEND_CLIENT_SECRET:-"test"}
            - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL:-"https://localhost/auth/realms/feasibility/protocol/openid-connect/token"}
            - CONFLUENCE_API_BASE_URL=${CONFLUENCE_API_BASE_URL:-""}
            - CONFLUENCE_PAGE_ID=${CONFLUENCE_PAGE_ID:-""}
            - CONF_USER=${CONF_USER:-"username"}
            - CONF_PW=${CONF_PW:-"password"}
            - WAIT_RESULT_SECS=${WAIT_RESULT_SECS:-60}
        volumes:
            - .:/opt/reportclient