services:
    feasibility-test-client:
        image: ghcr.io/medizininformatik-initiative/feasibility-monitoring:0.2.1
        environment:
            - BACKEND_BASE_URL=${BACKEND_BASE_URL:-"https://localhost/api/v1"} 
            - BACKEND_CLIENT_ID=${BACKEND_CLIENT_ID:-""} 
            - BACKEND_CLIENT_SECRET=${BACKEND_CLIENT_SECRET:-""}
            - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL:-""}
            - CONFLUENCE_API_BASE_URL=${CONFLUENCE_API_BASE_URL:-"https://myconfluence-rest-api-url"}
            - CONFLUENCE_PAGE_ID=${CONFLUENCE_PAGE_ID:-""}
            - CONF_USER=${CONF_USER:-""}
            - CONF_PW=${CONF_PW:-""}
            - WAIT_RESULT_SECS_FEAS=${WAIT_RESULT_SECS_FEAS:-60}
            - WAIT_RESULT_SECS_PING=${WAIT_RESULT_SECS_PING:-60}
            - SEND_TO_CONFLUENCE=${SEND_TO_CONFLUENCE:-"false"}
            - DSF_BASE_URL=${DSF_BASE_URL:-""}
            - EXECUTE_FEAS_TEST=${EXECUTE_FEAS_TEST:-"false"}
            - CONFLUENCE_PAGE_ID_FEAS=${CONFLUENCE_PAGE_ID_FEAS:-""}
            - EXECUTE_HISTORY_TEST=${EXECUTE_HISTORY_TEST:-"false"}
            - CONFLUENCE_PAGE_ID_HIST=${CONFLUENCE_PAGE_ID_HIST:-""}
            - HISTORY_TABLE_LEN=${HISTORY_TABLE_LEN:-14}
            - EXECUTE_DSF_PING_TEST=${EXECUTE_DSF_PING_TEST:-"false"}
            - CONFLUENCE_PAGE_ID_PING=${CONFLUENCE_PAGE_ID_PING:-""}
            - LOG_LEVEL=${LOG_LEVEL:-"INFO"}
        volumes:
            - ${LOCAL_DSF_CERT_PATH:-./cert/dsf-cert.cer}:/opt/reportclient/certs/dsf-cert.cer
            - ${LOCAL_DSF_KEY_PATH:-./cert/dsf-key.key}:/opt/reportclient/certs/dsf-key.key
            - ../config:/opt/reportclient/config
            - ../reports:/opt/reportclient/reports